POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "She Wants a Higher Profile for Black Skydivers. See How High.",
  "author": "Alina Tugend",
  "url": "https://nyti.ms/2PPwbCZ",
  "likes": 0
}