POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpoYXdlcyIsImlkIjoiNWYyYmUxMzRiOGQyYWQ3MjdmNjExOTgyIiwiaWF0IjoxNTk2NzExODczfQ.7i7RA0V-2u3Na01a_5Ieo2g4D9Sv15rYHCK1ajrBgLw

{
  "title": "She Wants a Higher Profile for Black Skydivers. See How High.",
  "author": "Alina Tugend",
  "url": "https://nyti.ms/2PPwbCZ",
  "likes": 0,
  "userId": "5f2be134b8d2ad727f611982"
}